name: LeetCode Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run LeetCode Synchronizer
        # Switch to the latest patched version
        uses: dos-m0nk3y/LeetCode-Synchronizer@v1.2.3 
        with:
          GITHUB_TOKEN: ${{ github.token }}
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
          LEETCODE_CSRF_TOKEN: ${{ secrets.LEETCODE_CSRF_TOKEN }}
